### ISSUE TITLE
attempt to index field 'rnn' (a nil value)

### ISSUE THREAD

**Issue by taineleau-zz** [coreylynch/grid-lstm#1]
``` sh
 th train.lua -model grid.lstm
using CUDA on GPU 0...
loading data files...
cutting off end of data so that the batches/sequences divide evenly
reshaping tensor...
data load done. Number of data batches in train: 423, val: 23, test: 0
vocab size: 65
creating an grid.lstm with 2 layers
number of parameters in the model: 0
cloning criterion
/usr/local/torch/install/bin/luajit: train.lua:315: attempt to index field 'rnn' (a nil value)
stack traceback:
    train.lua:315: in function 'opfunc'
    /usr/local/torch/install/share/lua/5.1/optim/adam.lua:33: in function 'adam'
    train.lua:381: in main chunk
    [C]: in function 'dofile'
    ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405ea0
```

Hi,  I configure as char-RNN's README and I could train char-rnn on my computer (so I suppose I set up the environment properly), but when it comes to grid-lstm, it failed. The error messages are as above.

Could you kindly tell me what's wrong with it?

Thanks!

**Comment by coreylynch** [comment]
Hi I was playing around with the adam optimizer and shouldn't have committed that change. [this commit](https://github.com/coreylynch/grid-lstm/commit/342577afa650e1beb23a7d44908e9043c6b34c62) reverts that change. I'd git pull these changes and retry.
