### ISSUE TITLE
No way to sample

### ISSUE THREAD

**Issue by Nyrt** [coreylynch/grid-lstm#2]
I'd like to be able to sample the results of the checkpoints in order to see if the network has developed longer dependency/more creativity than the vanilla LSTM, but there's no sample.lua file, and the default sample.lua can't handle the grid-lstm model.

**Comment by Nyrt** [comment]
changed line 105 to:
`if (checkpoint.opt.model == 'lstm' or checkpoint.opt.model == 'grid_lstm') then`

It's now getting 13 inputs instead of 7, what it was getting before, but it wants 14, and I'm not at all sure this is what the model expects.

**Comment by coreylynch** [comment]
Thanks for pointing this out! Commit a4d0c1ab7d66915e511859d7c5c23fa7f06d8a53 fixes this and I added an example to the README.
